### ISSUE TITLE
specifying organizations/teams in document

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-transition-guide#12]
(carried over from #11)

In various part of the Transition Guide (as well as other docs, for that matter) we mention various ETs and TTs (ET-W2AT, ET-OM, TT-WISMD, etc.).

Do/should we make these more generic (i.e. WMO, INFCOM)? Note this will also apply to some requirements in WTH, for example.

**Comment by golfvert** [comment]
When describing the Global Monitoring, I have used "WIS Operations and Monitoring team".
So, something in between, INFCOM (very formal and too high level for me) and ET-OM (a bit opaque). Not sure if it is the right thing or not...
