### ISSUE TITLE
Need to tell WIS Centres to include GTS properties in their notification messages

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-transition-guide#30]
Currently the Transition Guide only mentions the GTS Properties (see #20) in the section: "WIS2 to GTS Gateway operators". Would be useful to include this information in the section intended for those operating WIS Centres too - they may not read the section on temporary global services.

**Comment by golfvert** [comment]
It is already there in 6.1.3

NMCs that have implemented a WIS2 Node, and published all the data transmitted in the GTS on WIS2 can, if they wish, turn off their GTS system MSS and stop transmitting data in the GTS. When NMCs decide to decommission and turn off their GTS system MSS and stop transmitting their data in GTS, they shall include the GTS properties in the Notification Message as described in the WIS2 to GTS gateway technical requirements.

**Comment by 6a6d74** [comment]
Agreed. It's in the Guide ... although now section 5.2.3.1. For WIS Centres wishing to stop their MSS
