### ISSUE TITLE
LSP edits continued

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-transition-guide#54]
There some new revisions based on the latest preparation by LSP for publication.

**Comment by amilan17** [comment]
Question about sentence in section "[Guidance for WIS2 to GTS gateway operators](https://wmo-im.github.io/wis2-transition-guide/transition-guide/wis2-transition-guide-DRAFT.html#_3_2_3_2_guidance_for_wis2_to_gts_gateway_operators)": 
`As it is expected for data consumers, and to ensure resilient operation, the gateway should subscribe to notification messages from multiple Global Brokers. `

from the English editor:  
"I do not understand the phrase «As it is expected for (all) data consumers». The rest of the sentence makes sense to me. So any clarity as to what that first phrase means would be greatly appreciated."

"Does this mean:
`Both the gateway and its data consumers should subscribe to notification messages from multiple Global Brokers in order to ensure resilient operation.
`?"

**Comment by golfvert** [comment]
In my comments on the entire document, I suggested to remove that part of the sentence. If that part is unclear, I don't see why though, and considering that the rest is self sufficient, it can be removed.

**Comment by amilan17** [comment]
@golfvert WOW - thanks for your very quick response. 
To confirm you suggest that the sentence can be: 
 
`To ensure resilient operation, the gateway should subscribe to notification messages from multiple Global Brokers. `

**Comment by golfvert** [comment]
Yes. No need to rephrase what seems to be a problem for the editors.

**Comment by amilan17** [comment]
English editing of this publication is finished, the following PR is an update on minor revisions for main branch. Noting that it will be assigned WMO-No. 1323. 
[1323_Transition-to-WIS-2.0_en.pdf](https://github.com/user-attachments/files/16838229/1323_Transition-to-WIS-2.0_en.pdf)
